RSGShared = RSGShared or {}

RSGShared.Items = {
    -- Items
    ['bread']        = {['name'] = 'bread',        ['label'] = 'Bread Roll',    ['weight'] = 125, ['type'] = 'item', ['image'] = 'bread.png',        ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Bread Roll', ["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    ['horsebrush']   = {['name'] = 'horsebrush',   ['label'] = 'Horse Brush',   ['weight'] = 10,  ['type'] = 'item', ['image'] = 'horsebrush.png',   ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'brush used to clean your horse'},
    ['boatticket']   = {['name'] = 'boatticket',   ['label'] = 'Boat Ticket',   ['weight'] = 0,   ['type'] = 'item', ['image'] = 'boatticket.png',   ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for boat travel'},
    ['canoe']        = {['name'] = 'canoe',        ['label'] = 'Canoe',         ['weight'] = 500, ['type'] = 'item', ['image'] = 'canoe.png',        ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'deployable canoe'},
    ['moonshine']    = {['name'] = 'moonshine',    ['label'] = 'Moonshine',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'moonshine.png',    ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'best moonshine in town'},
    ['beer']         = {['name'] = 'beer',         ['label'] = 'Beer',          ['weight'] = 500, ['type'] = 'item', ['image'] = 'beer.png',         ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'bottle of beer'},
    ['whiskey']      = {['name'] = 'whiskey',      ['label'] = 'Whiskey',       ['weight'] = 500, ['type'] = 'item', ['image'] = 'whiskey.png',      ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'bottle of whiskey'},
    ['coffee']       = {['name'] = 'coffee',       ['label'] = 'Coffee',        ['weight'] = 500, ['type'] = 'item', ['image'] = 'coffee.png',       ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'cup of coffee'},
    ['bandage']      = {['name'] = 'bandage',      ['label'] = 'Bandage',       ['weight'] = 10,  ['type'] = 'item', ['image'] = 'bandage.png',      ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to improve your health'},
    ['firstaid']     = {['name'] = 'firstaid',     ['label'] = 'First Aid',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'firstaid.png',     ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by medics to improve your health'},
    ['sugarcube']    = {['name'] = 'sugarcube',    ['label'] = 'Sugar Cube',    ['weight'] = 10,  ['type'] = 'item', ['image'] = 'sugarcube.png',    ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'your horse may like these'},
    ['horselantern'] = {['name'] = 'horselantern', ['label'] = 'Horse Lantern', ['weight'] = 500, ['type'] = 'item', ['image'] = 'horselantern.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'horses need headlights!'},
    ['horseholster'] = {['name'] = 'horseholster', ['label'] = 'Horse Holster', ['weight'] = 500, ['type'] = 'item', ['image'] = 'horseholster.png', ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'horse holster'},
    ['stew']         = {['name'] = 'stew',         ['label'] = 'Hot Stew',      ['weight'] = 300, ['type'] = 'item', ['image'] = 'stew.png',         ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'hot homemade stew'},
    ['treasure1']    = {['name'] = 'treasure1',    ['label'] = 'Treasure Map',  ['weight'] = 50,  ['type'] = 'item', ['image'] = 'treasuremap.png',  ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'map for finding treasure'},
    ['notepad']      = {['name'] = 'notepad',      ['label'] = 'Notepad',       ['weight'] = 50,  ['type'] = 'item', ['image'] = 'notepad.png',      ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'for sending notes'},
    ['fieldbandage'] = {['name'] = 'fieldbandage', ['label'] = 'Field Bandage', ['weight'] = 50,  ['type'] = 'item', ['image'] = 'fieldbandage.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'patching yourself up'},
    ['canteen100']   = {['name'] = 'canteen100',   ['label'] = 'Canteen',       ['weight'] = 500, ['type'] = 'item', ['image'] = 'canteen.png',      ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Canteen 100% Full'},
    ['canteen75']    = {['name'] = 'canteen75',    ['label'] = 'Canteen',       ['weight'] = 400, ['type'] = 'item', ['image'] = 'canteen.png',      ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Canteen 75% Full'},
    ['canteen50']    = {['name'] = 'canteen50',    ['label'] = 'Canteen',       ['weight'] = 300, ['type'] = 'item', ['image'] = 'canteen.png',      ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Canteen 50% Full'},
    ['canteen25']    = {['name'] = 'canteen25',    ['label'] = 'Canteen',       ['weight'] = 200, ['type'] = 'item', ['image'] = 'canteen.png',      ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Canteen 25% Full'},
    ['canteen0']     = {['name'] = 'canteen0',     ['label'] = 'Empty Canteen', ['weight'] = 100, ['type'] = 'item', ['image'] = 'canteenempty.png', ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Empty Canteen'},

    -- saloon
    ['malt']   = {['name'] = 'malt',   ['label'] = 'Malt',   ['weight'] = 50, ['type'] = 'item', ['image'] = 'malt.png',   ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by saloons'},
    ['hops']   = {['name'] = 'hops',   ['label'] = 'Hops',   ['weight'] = 50, ['type'] = 'item', ['image'] = 'hops.png',   ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by saloons'},
    ['yeast']  = {['name'] = 'yeast',  ['label'] = 'Yeast',  ['weight'] = 50, ['type'] = 'item', ['image'] = 'yeast.png',  ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by saloons'},
    ['water']  = {['name'] = 'water',  ['label'] = 'Water',  ['weight'] = 50, ['type'] = 'item', ['image'] = 'water.png',  ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by saloons'},
    ['bottle'] = {['name'] = 'bottle', ['label'] = 'Bottle', ['weight'] = 50, ['type'] = 'item', ['image'] = 'bottle.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used by saloons'},

    -- beekeeper
    ['honeyframe']   = {['name'] = 'honeyframe',   ['label'] = 'Honey Frame',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'honeyframe.png',   ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Used for making honey'},
    ['honeycomb']    = {['name'] = 'honeycomb',    ['label'] = 'Honeycomb',     ['weight'] = 300, ['type'] = 'item', ['image'] = 'honeycomb.png',    ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Used for making honey'},
    ['honeypot']     = {['name'] = 'honeypot',     ['label'] = 'Honey Pot',     ['weight'] = 300, ['type'] = 'item', ['image'] = 'honeypot.png',     ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Used for making honey'},
    ['beeswax']      = {['name'] = 'beeswax',      ['label'] = 'Bees Wax',      ['weight'] = 100, ['type'] = 'item', ['image'] = 'beeswax.png',      ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from beehive'},

    -- horse training
    ['horsetrainingbrush']  = {['name'] = 'horsetrainingbrush',  ['label'] = 'Trainer Brush',  ['weight'] = 300, ['type'] = 'item', ['image'] = 'horsebrush.png',               ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['level'] = 0, ['description'] = 'brush used by a horse trainer'},
    ['horsetrainingcarrot'] = {['name'] = 'horsetrainingcarrot', ['label'] = 'Trainer Carrot', ['weight'] = 100, ['type'] = 'item', ['image'] = 'carrot.png',                   ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['level'] = 0, ['description'] = 'carrot used by a horse trainer'},
    ['horsereviver']        = {['name'] = 'horsereviver',        ['label'] = 'Horse Reviver',  ['weight'] = 100, ['type'] = 'item', ['image'] = 'consumable_horse_reviver.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to revive a horse'},
    ['saddlebag']           = {['name'] = 'saddlebag',           ['label'] = 'Saddlebag',      ['weight'] = 650, ['type'] = 'item', ['image'] = 'saddlebag.png',                ['unique'] = true,  ['useable'] = true,  ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = ''},

    -- farming items
    ['cornseed']     = {['name'] = 'cornseed',     ['label'] = 'Corn Seed',     ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ["corn"]         = {["name"] = "corn",         ["label"] = "Corn",          ["weight"] = 100, ["type"] = "item", ["image"] = "corn.png",        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ["description"] = "product from farming"},
    ['sugarseed']    = {['name'] = 'sugarseed',    ['label'] = 'Sugar Seed',    ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ["sugar"]        = {["name"] = "sugar",        ["label"] = "Sugar",         ["weight"] = 100, ["type"] = "item", ["image"] = "sugar.png",       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ["description"] = "product from farming"},
    ['tobaccoseed']  = {['name'] = 'tobaccoseed',  ['label'] = 'Tobacco Seed',  ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ['tobacco']      = {['name'] = 'tobacco',      ['label'] = 'Tobacco',       ['weight'] = 100, ['type'] = 'item', ['image'] = 'tobacco.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from farming'},
    ['carrotseed']   = {['name'] = 'carrotseed',   ['label'] = 'Carrot Seed',   ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ['carrot']       = {['name'] = 'carrot',       ['label'] = 'Carrot',        ['weight'] = 100, ['type'] = 'item', ['image'] = 'carrot.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from farming'},
    ['tomatoseed']   = {['name'] = 'tomatoseed',   ['label'] = 'Tomato Seed',   ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ['tomato']       = {['name'] = 'tomato',       ['label'] = 'Tomato',        ['weight'] = 100, ['type'] = 'item', ['image'] = 'tomato.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from farming'},
    ['broccoliseed'] = {['name'] = 'broccoliseed', ['label'] = 'Broccoli Seed', ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ['broccoli']     = {['name'] = 'broccoli',     ['label'] = 'Broccoli',      ['weight'] = 100, ['type'] = 'item', ['image'] = 'broccoli.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from farming'},
    ['potatoseed']   = {['name'] = 'potatoseed',   ['label'] = 'Potato Seed',   ['weight'] = 0,   ['type'] = 'item', ['image'] = 'seeds.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used in farming'},
    ['potato']       = {['name'] = 'potato',       ['label'] = 'Potato',        ['weight'] = 100, ['type'] = 'item', ['image'] = 'potato.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'product from farming'},
    ["wateringcan"]  = {["name"] = "wateringcan",  ["label"] = "Wateringcan",   ["weight"] = 300, ["type"] = "item", ["image"] = "wateringcan.png", ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ["description"] = "equipment for watering stuff"},
    ["bucket"]       = {["name"] = "bucket",       ["label"] = "Farm Bucket",   ["weight"] = 500, ["type"] = "item", ["image"] = "bucket.png",      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ["description"] = "farm equipment"},

    -- cooking
    ['raw_meat']    = {['name'] = 'raw_meat',    ['label'] = 'Raw Meat',    ['weight'] = 50,  ['type'] = 'item', ['image'] = 'raw_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'ready for cooking'},
    ['cooked_meat'] = {['name'] = 'cooked_meat', ['label'] = 'Cooked Meat', ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cooked_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'ready for cooking'},
    ['raw_fish']    = {['name'] = 'raw_fish',    ['label'] = 'Fish Meat',   ['weight'] = 50,  ['type'] = 'item', ['image'] = 'raw_fish.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'ready for cooking'},
    ['cooked_fish'] = {['name'] = 'cooked_fish', ['label'] = 'Cooked Fish', ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cooked_fish.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'ready for cooking'},
    ['campfire']    = {['name'] = 'campfire',    ['label'] = 'Camp Fire',   ['weight'] = 500, ['type'] = 'item', ['image'] = 'campfire.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for cooking'},

    -- gold prospecting
    ['goldpan']      = {['name'] = 'goldpan',      ['label'] = 'Gold Pan',      ['weight'] = 100, ['type'] = 'item', ['image'] = 'goldpan.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment for gold panning'},
    ['smallnugget']  = {['name'] = 'smallnugget',  ['label'] = 'Small Nugget',  ['weight'] = 100, ['type'] = 'item', ['image'] = 'smallnugget.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'small gold nugget'},
    ['mediumnugget'] = {['name'] = 'mediumnugget', ['label'] = 'Medium Nugget', ['weight'] = 200, ['type'] = 'item', ['image'] = 'mediumnugget.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'medium gold nugget'},
    ['largenugget']  = {['name'] = 'largenugget',  ['label'] = 'Large Nugget',  ['weight'] = 300, ['type'] = 'item', ['image'] = 'largenugget.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'large gold nugget'},
    ['goldsmelt']    = {['name'] = 'goldsmelt',    ['label'] = 'Gold Smelt',    ['weight'] = 300, ['type'] = 'item', ['image'] = 'goldsmelt.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment for gold smelting'},

    -- tobacco factory
    ['drytobacco'] = {['name'] = 'drytobacco', ['label'] = 'Dry Tobacco', ['weight'] = 100,  ['type'] = 'item', ['image'] = 'drytobacco.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'factory product'},
    ['cigar']      = {['name'] = 'cigar',      ['label'] = 'Cigar',       ['weight'] = 200,  ['type'] = 'item', ['image'] = 'cigar.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'factory product'},
    ['cigarbox']   = {['name'] = 'cigarbox',   ['label'] = 'Cigar Box',   ['weight'] = 2000, ['type'] = 'item', ['image'] = 'cigarbox.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'factory product'},

    -- a_c_bear_01
    ['perfect_bear_pelt']        = {['name'] = 'perfect_bear_pelt',        ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bear_pelt']           = {['name'] = 'good_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bear_pelt']           = {['name'] = 'poor_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bearblack_01
    ['perfect_black_bear_pelt']  = {['name'] = 'perfect_black_bear_pelt',  ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_black_bear_pelt']     = {['name'] = 'good_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_black_bear_pelt']     = {['name'] = 'poor_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_boar_01
    ['perfect_boar_pelt']        = {['name'] = 'perfect_boar_pelt',        ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_boar_pelt']           = {['name'] = 'good_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_boar_pelt']           = {['name'] = 'poor_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buck_01
    ['perfect_buck_pelt']        = {['name'] = 'perfect_buck_pelt',        ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buck_pelt']           = {['name'] = 'good_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buck_pelt']           = {['name'] = 'poor_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buffalo_01
    ['perfect_buffalo_pelt']     = {['name'] = 'perfect_buffalo_pelt',     ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buffalo_pelt']        = {['name'] = 'good_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buffalo_pelt']        = {['name'] = 'poor_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bull_01
    ['perfect_bull_pelt']        = {['name'] = 'perfect_bull_pelt',        ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bull_pelt']           = {['name'] = 'good_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bull_pelt']           = {['name'] = 'poor_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cougar_01
    ['perfect_cougar_pelt']      = {['name'] = 'perfect_cougar_pelt',      ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cougar_pelt']         = {['name'] = 'good_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cougar_pelt']         = {['name'] = 'poor_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cow
    ['perfect_cow_pelt']         = {['name'] = 'perfect_cow_pelt',         ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cow_pelt']            = {['name'] = 'good_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cow_pelt']            = {['name'] = 'poor_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_coyote_01
    ['perfect_coyote_pelt']      = {['name'] = 'perfect_coyote_pelt',      ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_coyote_pelt']         = {['name'] = 'good_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_coyote_pelt']         = {['name'] = 'poor_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_deer_01
    ['perfect_deer_pelt']        = {['name'] = 'perfect_deer_pelt',        ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_deer_pelt']           = {['name'] = 'good_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_deer_pelt']           = {['name'] = 'poor_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_elk_01
    ['perfect_elk_pelt']         = {['name'] = 'perfect_elk_pelt',         ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_elk_pelt']            = {['name'] = 'good_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_elk_pelt']            = {['name'] = 'poor_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_fox_01
    ['perfect_fox_pelt']         = {['name'] = 'perfect_fox_pelt',         ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_fox_pelt']            = {['name'] = 'good_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_fox_pelt']            = {['name'] = 'poor_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_goat_01
    ['perfect_goat_pelt']        = {['name'] = 'perfect_goat_pelt',        ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_goat_pelt']           = {['name'] = 'good_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_goat_pelt']           = {['name'] = 'poor_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_javelina_01
    ['perfect_javelina_pelt']    = {['name'] = 'perfect_javelina_pelt',    ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_javelina_pelt']       = {['name'] = 'good_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_javelina_pelt']       = {['name'] = 'poor_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_moose_01
    ['perfect_moose_pelt']       = {['name'] = 'perfect_moose_pelt',       ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_moose_pelt']          = {['name'] = 'good_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_moose_pelt']          = {['name'] = 'poor_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_ox_01
    ['perfect_ox_pelt']          = {['name'] = 'perfect_ox_pelt',          ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_ox_pelt']             = {['name'] = 'good_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_ox_pelt']             = {['name'] = 'poor_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_panther_01
    ['perfect_panther_pelt']     = {['name'] = 'perfect_panther_pelt',     ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_panther_pelt']        = {['name'] = 'good_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_panther_pelt']        = {['name'] = 'poor_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pig_01
    ['perfect_pig_pelt']         = {['name'] = 'perfect_pig_pelt',         ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pig_pelt']            = {['name'] = 'good_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pig_pelt']            = {['name'] = 'poor_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pronghorn_01
    ['perfect_pronghorn_pelt']   = {['name'] = 'perfect_pronghorn_pelt',   ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pronghorn_pelt']      = {['name'] = 'good_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pronghorn_pelt']      = {['name'] = 'poor_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bighornram_01
    ['perfect_bighornram_pelt']  = {['name'] = 'perfect_bighornram_pelt',  ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bighornram_pelt']     = {['name'] = 'good_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bighornram_pelt']     = {['name'] = 'poor_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_sheep_01
    ['perfect_sheep_pelt']       = {['name'] = 'perfect_sheep_pelt',       ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_sheep_pelt']          = {['name'] = 'good_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_sheep_pelt']          = {['name'] = 'poor_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_wolf
    ['perfect_wolf_pelt']        = {['name'] = 'perfect_wolf_pelt',        ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_wolf_pelt']           = {['name'] = 'good_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_wolf_pelt']           = {['name'] = 'poor_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_alligator_03
    ['perfect_alligator_pelt']   = {['name'] = 'perfect_alligator_pelt',   ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_alligator_pelt']      = {['name'] = 'good_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_alligator_pelt']      = {['name'] = 'poor_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- mp_a_c_alligator_01
    ['legendary_alligator_pelt'] = {['name'] = 'legendary_alligator_pelt', ['label'] = 'Leg Alligator Pelt', ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- A_C_Beaver_01
    ['legendary_beaver_pelt']    = {['name'] = 'legendary_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_beaver_01
    ['legendary_moon_beaver_pelt']    = {['name'] = 'legendary_moon_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_beaver_01
    ['legendary_zizi_beaver_pelt']    = {['name'] = 'legendary_zizi_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_beaver_01
    ['legendary_night_beaver_pelt']    = {['name'] = 'legendary_night_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_boar_01
    ['legendary_boar_pelt']      = {['name'] = 'legendary_boar_pelt',      ['label'] = 'Leg Boar Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_cougar_01
    ['legendary_cougar_pelt']    = {['name'] = 'legendary_cougar_pelt',    ['label'] = 'Leg Cougar Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_coyote_01
    ['legendary_coyote_pelt']    = {['name'] = 'legendary_coyote_pelt',    ['label'] = 'Leg Coyote Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_panther_01
    ['legendary_panther_pelt']   = {['name'] = 'legendary_panther_pelt',   ['label'] = 'Leg Panther Pelt',   ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_wolf_01
    ['legendary_wolf_pelt']      = {['name'] = 'legendary_wolf_pelt',      ['label'] = 'Leg Wolf Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- a_c_raccoon_01
    ['perfect_raccoon_pelt']   = {['name'] = 'perfect_raccoon_pelt',   ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_raccoon_pelt']      = {['name'] = 'good_raccoon_pelt',      ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_raccoon_pelt']      = {['name'] = 'poor_raccoon_pelt',      ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},

    -- fish
    ['a_c_fishbluegil_01_ms']        = {['name'] = 'a_c_fishbluegil_01_ms',        ['label'] = 'Blue Gil (M)',         ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_bluegill.png',         ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishbluegil_01_sm']        = {['name'] = 'a_c_fishbluegil_01_sm',        ['label'] = 'Blue Gil (S)',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_bluegill.png',         ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishbullheadcat_01_ms']    = {['name'] = 'a_c_fishbullheadcat_01_ms',    ['label'] = 'Bullhead Cat (M)',     ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_bullhead_catfish.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishbullheadcat_01_sm']    = {['name'] = 'a_c_fishbullheadcat_01_sm',    ['label'] = 'Bullhead Cat (S)',     ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_bullhead_catfish.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishchainpickerel_01_ms']  = {['name'] = 'a_c_fishchainpickerel_01_ms',  ['label'] = 'Chain Pickerel (M)',   ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_chain_pickerel.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishchainpickerel_01_sm']  = {['name'] = 'a_c_fishchainpickerel_01_sm',  ['label'] = 'Chain Pickerel (S)',   ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_chain_pickerel.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishchannelcatfish_01_lg'] = {['name'] = 'a_c_fishchannelcatfish_01_lg', ['label'] = 'Channel Catfish (L)',  ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_channel_catfish.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishchannelcatfish_01_xl'] = {['name'] = 'a_c_fishchannelcatfish_01_xl', ['label'] = 'Channel Catfish (EL)', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'provision_fish_channel_catfish.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishlakesturgeon_01_lg']   = {['name'] = 'a_c_fishlakesturgeon_01_lg',   ['label'] = 'Lake Sturgeon (L)',    ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_lake_sturgeon.png',    ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishlargemouthbass_01_lg'] = {['name'] = 'a_c_fishlargemouthbass_01_lg', ['label'] = 'Large Mouth Bass (L)', ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_largemouth_bass.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishlargemouthbass_01_ms'] = {['name'] = 'a_c_fishlargemouthbass_01_ms', ['label'] = 'Large Mouth Bass (M)', ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_largemouth_bass.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishlongnosegar_01_lg']    = {['name'] = 'a_c_fishlongnosegar_01_lg',    ['label'] = 'Long Nose Gar (L)',    ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_longnose_gar.png',     ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishmuskie_01_lg']         = {['name'] = 'a_c_fishmuskie_01_lg',         ['label'] = 'Muskie (L)',           ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_muskie.png',           ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishnorthernpike_01_lg']   = {['name'] = 'a_c_fishnorthernpike_01_lg',   ['label'] = 'Northern Pike (L)',    ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_northern_pike.png',    ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishperch_01_ms']          = {['name'] = 'a_c_fishperch_01_ms',          ['label'] = 'Perch (M)',            ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_perch.png',            ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishperch_01_sm']          = {['name'] = 'a_c_fishperch_01_sm',          ['label'] = 'Perch (S)',            ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_perch.png',            ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishrainbowtrout_01_lg']   = {['name'] = 'a_c_fishrainbowtrout_01_lg',   ['label'] = 'Rainbow Trout (L)',    ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_speckled_trout.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishrainbowtrout_01_ms']   = {['name'] = 'a_c_fishrainbowtrout_01_ms',   ['label'] = 'Rainbow Trout (M)',    ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_speckled_trout.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishredfinpickerel_01_ms'] = {['name'] = 'a_c_fishredfinpickerel_01_ms', ['label'] = 'Red Fin Pickerel (M)', ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_redfin_pickerel.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishredfinpickerel_01_sm'] = {['name'] = 'a_c_fishredfinpickerel_01_sm', ['label'] = 'Red Fin Pickerel (S)', ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_redfin_pickerel.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishrockbass_01_ms']       = {['name'] = 'a_c_fishrockbass_01_ms',       ['label'] = 'Rock Bass (M)',        ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_rock_bass.png',        ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishrockbass_01_sm']       = {['name'] = 'a_c_fishrockbass_01_sm',       ['label'] = 'Rock Bass (S)',        ['weight'] = 300,  ['type'] = 'item', ['image'] = 'provision_fish_rock_bass.png',        ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishsalmonsockeye_01_lg']  = {['name'] = 'a_c_fishsalmonsockeye_01_lg',  ['label'] = 'Salmon Sockeye (L)',   ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_sockeye_salmon.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishsalmonsockeye_01_ml']  = {['name'] = 'a_c_fishsalmonsockeye_01_ml',  ['label'] = 'Salmon Sockeye (ML)',  ['weight'] = 800,  ['type'] = 'item', ['image'] = 'provision_fish_sockeye_salmon.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishsalmonsockeye_01_ms']  = {['name'] = 'a_c_fishsalmonsockeye_01_ms',  ['label'] = 'Salmon Sockeye (M)',   ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_sockeye_salmon.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishsmallmouthbass_01_lg'] = {['name'] = 'a_c_fishsmallmouthbass_01_lg', ['label'] = 'Small Mouth Bass (L)', ['weight'] = 900,  ['type'] = 'item', ['image'] = 'provision_fish_smallmouth_bass.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['a_c_fishsmallmouthbass_01_ms'] = {['name'] = 'a_c_fishsmallmouthbass_01_ms', ['label'] = 'Small Mouth Bass (M)', ['weight'] = 600,  ['type'] = 'item', ['image'] = 'provision_fish_smallmouth_bass.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},

    -- fishing bait
    ['p_baitbread01x']   = {['name'] = 'p_baitbread01x',   ['label'] = 'Bread Bait',    ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_bread.png',    ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_baitcorn01x']    = {['name'] = 'p_baitcorn01x',    ['label'] = 'Corn Bait',     ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_corn.png',     ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_baitcheese01x']  = {['name'] = 'p_baitcheese01x',  ['label'] = 'Cheese Bait',   ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_cheese.png',   ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_baitworm01x']    = {['name'] = 'p_baitworm01x',    ['label'] = 'Worm Bait',     ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_worm.png',     ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_baitcricket01x'] = {['name'] = 'p_baitcricket01x', ['label'] = 'Cricket Bait',  ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_cricket.png',  ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_crawdad01x']     = {['name'] = 'p_crawdad01x',     ['label'] = 'Crawfish Bait', ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_crayfish.png', ['unique'] = false, ['useable'] = true,    ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    -- fishing lures
    ['p_finishedragonfly01x']          = {['name'] = 'p_finishedragonfly01x',          ['label'] = 'Dragonfly Lure',           ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_leg_lure_river.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_finisdfishlure01x']            = {['name'] = 'p_finisdfishlure01x',            ['label'] = 'Fish Lure',                ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_finishdcrawd01x']              = {['name'] = 'p_finishdcrawd01x',              ['label'] = 'Crawfish Lure',            ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_leg_lure_swamp.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_finishedragonflylegendary01x'] = {['name'] = 'p_finishedragonflylegendary01x', ['label'] = 'Legendary Dragonfly Lure', ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_lure_lake.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_finisdfishlurelegendary01x']   = {['name'] = 'p_finisdfishlurelegendary01x',   ['label'] = 'Legendary Fish Lure',      ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_lure_lake.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_finishdcrawdlegendary01x']     = {['name'] = 'p_finishdcrawdlegendary01x',     ['label'] = 'Legendary Crawfish Lure',  ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_lure_lake.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_lgoc_spinner_v4']              = {['name'] = 'p_lgoc_spinner_v4',              ['label'] = 'Spinner',                  ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},
    ['p_lgoc_spinner_v6']              = {['name'] = 'p_lgoc_spinner_v6',              ['label'] = 'Improved Spinner',         ['weight'] = 10, ['type'] = 'item', ['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used for fishing'},

    -- petshop
    ['foxhound']     = {['name'] = 'foxhound',     ['label'] = 'Fox Hound',     ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_americanfoxhound.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'American Foxhound'},
    ['sheperd']      = {['name'] = 'sheperd',      ['label'] = 'Shepherd',      ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_australianshepherd.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Australian Sheperd'},
    ['coonhound']    = {['name'] = 'coonhound',    ['label'] = 'Coon Hound',    ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_bluetickcoonhound.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Bluetick Coonhound'},
    ['catahoulacur'] = {['name'] = 'catahoulacur', ['label'] = 'Catahoula Cur', ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_catahoularcur.png',      ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Catahoula Cur'},
    ['bayretriever'] = {['name'] = 'bayretriever', ['label'] = 'Retriever',     ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_chesbayretriever.png',   ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Ches Bay Retriever'},
    ['collie']       = {['name'] = 'collie',       ['label'] = 'Collie',        ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_collie.png',             ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Collie'},
    ['hound']        = {['name'] = 'hound',        ['label'] = 'Hound',         ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_hound.png',              ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Hound'},
    ['husky']        = {['name'] = 'husky',        ['label'] = 'Husky',         ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_husky.png',              ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Husky'},
    ['lab']          = {['name'] = 'lab',          ['label'] = 'Lab',           ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_lab.png',                ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Lab'},
    ['poodle']       = {['name'] = 'poodle',       ['label'] = 'Poodle',        ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_poodle.png',             ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poodle'},
    ['street']       = {['name'] = 'street',       ['label'] = 'Street',        ['weight'] = 500, ['type'] = 'item', ['image'] = 'animal_dog_street.png',             ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Street'},

    -- to support indian tobacco
    ['indtobaccoseed'] = {['name'] = 'indtobaccoseed', ['label'] = 'Indian Seed',    ['weight'] = 0,   ['type'] = 'item', ['image'] = 'indtobaccoseed.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'indian tobacco seed'},
    ['indtobacco']     = {['name'] = 'indtobacco',     ['label'] = 'Indian Tobacco', ['weight'] = 10,  ['type'] = 'item', ['image'] = 'indtobacco.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'indian tobacco'},
    ['fertilizer']     = {['name'] = 'fertilizer',     ['label'] = 'Fertilizer',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'fertilizer.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'feed for growing plants'},
    ['indiancigar']    = {['name'] = 'indiancigar',    ['label'] = 'Indian Cigar',   ['weight'] = 50,  ['type'] = 'item', ['image'] = 'indiancigar.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'indian cigar'},

    -- to support moonshiner
    ['moonshinekit'] = {['name'] = 'moonshinekit', ['label'] = 'Moonshine Kit', ['weight'] = 500, ['type'] = 'item', ['image'] = 'moonshinekit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to construct a moonshine'},

    -- to support bank heist
    ['dynamite']  = {['name'] = 'dynamite',  ['label'] = 'Dynamite',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'dynamite.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'for blowing stuff up'},
    ['goldbar']   = {['name'] = 'goldbar',   ['label'] = 'Gold Bar',   ['weight'] = 500, ['type'] = 'item', ['image'] = 'goldbar.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'solid gold bar'},
    ['goldwatch'] = {['name'] = 'goldwatch', ['label'] = 'Gold Watch', ['weight'] = 100, ['type'] = 'item', ['image'] = 'goldwatch.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'solid gold watch'},
    ['lockpick']  = {['name'] = 'lockpick',  ['label'] = 'Lockpick',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'lockpick.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'for picking locks'},

    -- bpos
    ['bposhovel']  = {['name'] = 'bposhovel',  ['label'] = 'BPO Shovel',  ['weight'] = 0, ['type'] = 'item', ['image'] = 'bposhovel.png',  ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'blueprint original'},
    ['bpoaxe']     = {['name'] = 'bpoaxe',     ['label'] = 'BPO Axe',     ['weight'] = 0, ['type'] = 'item', ['image'] = 'bpoaxe.png',     ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'blueprint original'},
    ['bpopickaxe'] = {['name'] = 'bpopickaxe', ['label'] = 'BPO PickAxe', ['weight'] = 0, ['type'] = 'item', ['image'] = 'bpopickaxe.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'blueprint original'},

    -- bpcs
    ['bpcshovel']  = {['name'] = 'bpcshovel',  ['label'] = 'BPC Shovel',  ['weight'] = 0, ['type'] = 'item', ['image'] = 'bpcshovel.png',  ['unique'] = true, ['useable'] = true,    ['shouldClose'] = true,    ['combinable'] = nil,    ['level'] = 0,    ['description'] = '3 x Steel 1 x Wood'},
    ['bpcaxe']     = {['name'] = 'bpcaxe',     ['label'] = 'BPC Axe',     ['weight'] = 0, ['type'] = 'item', ['image'] = 'bpcaxe.png',     ['unique'] = true, ['useable'] = true,    ['shouldClose'] = true,    ['combinable'] = nil,    ['level'] = 0,    ['description'] = '3 x Steel 1 x Wood'},
    ['bpcpickaxe'] = {['name'] = 'bpcpickaxe', ['label'] = 'BPC PickAxe', ['weight'] = 0, ['type'] = 'item', ['image'] = 'bpcpickaxe.png', ['unique'] = true, ['useable'] = true,    ['shouldClose'] = true,    ['combinable'] = nil,    ['level'] = 0,    ['description'] = '3 x Steel 1 x Wood'},

    -- item
    ['shovel']  = {['name'] = 'shovel',  ['label'] = 'Shovel',  ['weight'] = 100, ['type'] = 'item', ['image'] = 'shovel.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment for digging'},
    ['axe']     = {['name'] = 'axe',     ['label'] = 'Axe',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'axe.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment for chopping'},
    ['pickaxe'] = {['name'] = 'pickaxe', ['label'] = 'PickAxe', ['weight'] = 100, ['type'] = 'item', ['image'] = 'pickaxe.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment for mining'},

    -- materials
    ['copper']   = {['name'] = 'copper',   ['label'] = 'Copper',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'copper.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'crafting material'},
    ['aluminum'] = {['name'] = 'aluminum', ['label'] = 'Aluminum', ['weight'] = 100, ['type'] = 'item', ['image'] = 'aluminum.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'crafting material'},
    ['iron']     = {['name'] = 'iron',     ['label'] = 'Iron',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'iron.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'crafting material'},
    ['steel']    = {['name'] = 'steel',    ['label'] = 'Steel',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'steel.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'crafting material'},
    ['wood']     = {['name'] = 'wood',     ['label'] = 'Wood',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'wood.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'crafting material'},

    -- weapon crafting parts
    ['trigger']  = { ['name'] = 'trigger',  ['label'] = 'Trigger',  ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['hammer']   = { ['name'] = 'hammer',   ['label'] = 'Hammer',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['barrel']   = { ['name'] = 'barrel',   ['label'] = 'Barrel',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['spring']   = { ['name'] = 'spring',   ['label'] = 'Spring',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['frame']    = { ['name'] = 'frame',    ['label'] = 'Frame',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['grip']     = { ['name'] = 'grip',     ['label'] = 'Grip',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['cylinder'] = { ['name'] = 'cylinder', ['label'] = 'Cylinder', ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['stock']    = { ['name'] = 'stock',    ['label'] = 'Stock',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['sight']    = { ['name'] = 'sight',    ['label'] = 'Sight',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['bolt']     = { ['name'] = 'bolt',     ['label'] = 'Bolt',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['sling']    = { ['name'] = 'sling',    ['label'] = 'Sling',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    ['action']   = { ['name'] = 'action',   ['label'] = 'Action',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'weaponpart.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'weapon crafting part'},
    
    -- weaponsmith items
    ['cleankit'] = { ['name'] = 'cleankit',  ['label'] = 'Cleaning Kit', ['weight'] = 100, ['type'] = 'item', ['image'] = 'cleankit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'for cleaning weapons'},

    --ammo
    ['ammo_repeater'] = {['name'] = 'ammo_repeater', ['label'] = 'Repeater (N)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater Ammo'},
    ['ammo_revolver'] = {['name'] = 'ammo_revolver', ['label'] = 'Revolver (N)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver Ammo'},
    ['ammo_rifle']    = {['name'] = 'ammo_rifle',    ['label'] = 'Rifle (N)',    ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle Ammo'},
    ['ammo_rifle_elephant']    = {['name'] = 'ammo_rifle_elephant',    ['label'] = 'Elephant Rifle (N)',    ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Elephant Rifle Ammo'},
    ['ammo_pistol']   = {['name'] = 'ammo_pistol',   ['label'] = 'Pistol (N)',   ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol Ammo'},
    ['ammo_shotgun']  = {['name'] = 'ammo_shotgun',  ['label'] = 'Shotgun (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_shotgun.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Shotgun Ammo'},
    ['ammo_arrow']    = {['name'] = 'ammo_arrow',    ['label'] = 'Arrow (N)',    ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_arrow.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Arrow'},
    ['ammo_varmint']  = {['name'] = 'ammo_varmint',  ['label'] = 'Varmint (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Varmint Ammo'},
    
    -- revolver
    ['weapon_revolver_cattleman']              = {['name'] = 'weapon_revolver_cattleman',              ['attachPoint'] = 2,  ['label'] = 'Cattleman',            ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_cattleman.png',              ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_cattleman_mexican']      = {['name'] = 'weapon_revolver_cattleman_mexican',      ['attachPoint'] = 2,  ['label'] = 'Cattleman Mexican',    ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_cattleman_mexican.png',      ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_doubleaction_gambler']   = {['name'] = 'weapon_revolver_doubleaction_gambler',   ['attachPoint'] = 2,  ['label'] = 'Gambler',              ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_doubleaction_gambler.png',   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_schofield']              = {['name'] = 'weapon_revolver_schofield',              ['attachPoint'] = 2,  ['label'] = 'Schofield',            ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_schofield.png',              ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_lemat']                  = {['name'] = 'weapon_revolver_lemat',                  ['attachPoint'] = 2,  ['label'] = 'LeMat',                ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_lemat.png',                  ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_navy']                   = {['name'] = 'weapon_revolver_navy',                   ['attachPoint'] = 2,  ['label'] = 'Navy',                 ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_navy.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    ['weapon_revolver_navy_crossover']         = {['name'] = 'weapon_revolver_navy_crossover',         ['attachPoint'] = 2,  ['label'] = 'Navy Crossover',       ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REVOLVER', ['image'] = 'weapon_revolver_navy_crossover.png',         ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Revolver Ammo'},
    -- pistol    
    ['weapon_pistol_volcanic']                 = {['name'] = 'weapon_pistol_volcanic',                 ['attachPoint'] = 2,  ['label'] = 'Volcanic',             ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',   ['image'] = 'weapon_pistol_volcanic.png',                 ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Pistol Ammo'},
    ['weapon_pistol_m1899']                    = {['name'] = 'weapon_pistol_m1899',                    ['attachPoint'] = 2,  ['label'] = 'M1899',                ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',   ['image'] = 'weapon_pistol_m1899.png',                    ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Pistol Ammo'},
    ['weapon_pistol_mauser']                   = {['name'] = 'weapon_pistol_mauser',                   ['attachPoint'] = 2,  ['label'] = 'Mauser',               ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',   ['image'] = 'weapon_pistol_mauser.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Pistol Ammo'},
    ['weapon_pistol_semiauto']                 = {['name'] = 'weapon_pistol_semiauto',                 ['attachPoint'] = 2,  ['label'] = 'Semi-Auto',            ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',   ['image'] = 'weapon_pistol_semiauto.png',                 ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Pistol Ammo'},
    -- repeater
    ['weapon_repeater_carbine']                = {['name'] = 'weapon_repeater_carbine',                ['attachPoint'] = 9,  ['label'] = 'Carbine',              ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REPEATER', ['image'] = 'weapon_repeater_carbine.png',                ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Repeater Ammo'},
    ['weapon_repeater_winchester']             = {['name'] = 'weapon_repeater_winchester',             ['attachPoint'] = 9,  ['label'] = 'Winchester',           ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REPEATER', ['image'] = 'weapon_repeater_winchester.png',             ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Repeater Ammo'},
    ['weapon_repeater_henry']                  = {['name'] = 'weapon_repeater_henry',                  ['attachPoint'] = 9,  ['label'] = 'Henry',                ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REPEATER', ['image'] = 'weapon_repeater_henry.png',                  ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Repeater Ammo'},
    ['weapon_repeater_evans']                  = {['name'] = 'weapon_repeater_evans',                  ['attachPoint'] = 9,  ['label'] = 'Evans',                ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_REPEATER', ['image'] = 'weapon_repeater_evans.png',                  ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Repeater Ammo'},
    -- rifle
    ['weapon_rifle_varmint']                   = {['name'] = 'weapon_rifle_varmint',                   ['attachPoint'] = 9,  ['label'] = 'Varmint',              ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_rifle_varmint.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    ['weapon_rifle_springfield']               = {['name'] = 'weapon_rifle_springfield',               ['attachPoint'] = 9,  ['label'] = 'Springfield',          ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_rifle_springfield.png',               ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    ['weapon_rifle_boltaction']                = {['name'] = 'weapon_rifle_boltaction',                ['attachPoint'] = 9,  ['label'] = 'Boltaction',           ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_rifle_boltaction.png',                ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    ['weapon_rifle_elephant']                  = {['name'] = 'weapon_rifle_elephant',                  ['attachPoint'] = 9,  ['label'] = 'Elephant',             ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_rifle_elephant.png',                  ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    -- shotgun
    ['weapon_shotgun_doublebarrel']            = {['name'] = 'weapon_shotgun_doublebarrel',            ['attachPoint'] = 9,  ['label'] = 'Shotgun',              ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_doublebarrel.png',            ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    ['weapon_shotgun_doublebarrel_exotic']     = {['name'] = 'weapon_shotgun_doublebarrel_exotic',     ['attachPoint'] = 9,  ['label'] = 'Exotic Shotgun',       ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_doublebarrel_exotic.png',     ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    ['weapon_shotgun_sawedoff']                = {['name'] = 'weapon_shotgun_sawedoff',                ['attachPoint'] = 9,  ['label'] = 'Sawedoff Shotgun',     ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_sawedoff.png',                ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    ['weapon_shotgun_semiauto']                = {['name'] = 'weapon_shotgun_semiauto',                ['attachPoint'] = 9,  ['label'] = 'SA Shotgun',           ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_semiauto.png',                ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    ['weapon_shotgun_pump']                    = {['name'] = 'weapon_shotgun_pump',                ['attachPoint'] = 9,  ['label'] = 'SA Shotgun',           ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_pump.png',                    ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    ['weapon_shotgun_repeating']               = {['name'] = 'weapon_shotgun_repeating',                ['attachPoint'] = 9,  ['label'] = 'SA Shotgun',           ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN',  ['image'] = 'weapon_shotgun_repeating.png',               ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Shotgun Ammo'},
    -- sniperrifle
    ['weapon_sniperrifle_rollingblock']        = {['name'] = 'weapon_sniperrifle_rollingblock',        ['attachPoint'] = 10, ['label'] = 'Rollingblock',         ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_sniperrifle_rollingblock.png',        ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    ['weapon_sniperrifle_rollingblock_exotic'] = {['name'] = 'weapon_sniperrifle_rollingblock_exotic', ['attachPoint'] = 10, ['label'] = 'Exotic Rrollingblock', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_sniperrifle_rollingblock_exotic.png', ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    ['weapon_sniperrifle_carcano']             = {['name'] = 'weapon_sniperrifle_carcano',             ['attachPoint'] = 10, ['label'] = 'Carcano',              ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',    ['image'] = 'weapon_sniperrifle_carcano.png',             ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Rifle Ammo'},
    -- bow
    ['weapon_bow']                             = {['name'] = 'weapon_bow',                             ['attachPoint'] = 7,  ['label'] = 'Bow',                  ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = 'AMMO_ARROW',    ['image'] = 'weapon_bow.png',                             ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Arrow Ammo'},
    ['weapon_bow_improved']                    = {['name'] = 'weapon_bow_improved',                    ['attachPoint'] = 7,  ['label'] = 'Improved Bow',         ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = 'AMMO_ARROW',    ['image'] = 'weapon_bow_improved.png',                    ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Takes Arrow Ammo'},
    -- lasso
    ['weapon_lasso']                           = {['name'] = 'weapon_lasso',                           ['attachPoint'] = 5,  ['label'] = 'Lasso',                ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_lasso.png',                           ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_lasso_reinforced']                = {['name'] = 'weapon_lasso_reinforced',                ['attachPoint'] = 5,  ['label'] = 'Improved Lasso',       ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_lasso_reinforced.png',                ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    -- melee
    ['weapon_melee_knife']                     = {['name'] = 'weapon_melee_knife',                     ['attachPoint'] = 4,  ['label'] = 'Knife',                ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_knife.png',                     ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_knife_jawbone']             = {['name'] = 'weapon_melee_knife_jawbone',             ['attachPoint'] = 4,  ['label'] = 'Jawbone Knife',        ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_knife_jawbone.png',             ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_hammer']                    = {['name'] = 'weapon_melee_hammer',                    ['attachPoint'] = 13, ['label'] = 'Hammer',               ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_hammer.png',                    ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_cleaver']                   = {['name'] = 'weapon_melee_cleaver',                   ['attachPoint'] = 3,  ['label'] = 'Cleaver',              ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_cleaver.png',                   ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_lantern']                   = {['name'] = 'weapon_melee_lantern',                   ['attachPoint'] = 11, ['label'] = 'Lantern',              ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_lantern.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_davy_lantern']              = {['name'] = 'weapon_melee_davy_lantern',              ['attachPoint'] = 11, ['label'] = 'Davy Lantern',         ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_davy_lantern.png',              ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_lantern_halloween']         = {['name'] = 'weapon_melee_lantern_halloween',         ['attachPoint'] = 11, ['label'] = 'Halloween Lantern',    ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_lantern_halloween.png',         ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_torch']                     = {['name'] = 'weapon_melee_torch',                     ['attachPoint'] = 13, ['label'] = 'Wooden Torch',         ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_torch.png',                     ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_hatchet']                   = {['name'] = 'weapon_melee_hatchet',                   ['attachPoint'] = 13, ['label'] = 'Hatchet',              ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_hatchet.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_melee_machete']                   = {['name'] = 'weapon_melee_machete',                   ['attachPoint'] = 13, ['label'] = 'Machete',              ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_melee_machete.png',                   ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    -- thrown
    ['weapon_thrown_throwing_knives']          = {['name'] = 'weapon_thrown_throwing_knives',          ['attachPoint'] = 6,  ['label'] = 'Throwing Knives',      ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_throwing_knives.png',          ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_tomahawk']                 = {['name'] = 'weapon_thrown_tomahawk',                 ['attachPoint'] = 6,  ['label'] = 'Throwable Axe',        ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_tomahawk.png',                 ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_tomahawk_ancient']         = {['name'] = 'weapon_thrown_tomahawk_ancient',         ['attachPoint'] = 6,  ['label'] = 'Throwable Old Axe',    ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_tomahawk_ancient.png',         ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_bolas']                    = {['name'] = 'weapon_thrown_bolas',                    ['attachPoint'] = 6,  ['label'] = 'Standard Bolas',       ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_bolas.png',                    ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_bolas_hawkmoth']           = {['name'] = 'weapon_thrown_bolas_hawkmoth',           ['attachPoint'] = 6,  ['label'] = 'Hawkmoth Bolas',       ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_bolas_hawkmoth.png',           ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_bolas_ironspiked']         = {['name'] = 'weapon_thrown_bolas_ironspiked',         ['attachPoint'] = 6,  ['label'] = 'Ironspiked Bolas',     ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_bolas_ironspiked.png',         ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_bolas_intertwined']        = {['name'] = 'weapon_thrown_bolas_intertwined',        ['attachPoint'] = 6,  ['label'] = 'Intertwined Bolas',    ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_bolas_intertwined.png',        ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_dynamite']                 = {['name'] = 'weapon_thrown_dynamite',                 ['attachPoint'] = 6,  ['label'] = 'Dynamite',             ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_dynamite.png',                 ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_molotov']                  = {['name'] = 'weapon_thrown_molotov',                  ['attachPoint'] = 6,  ['label'] = 'Molotov',              ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_molotov.png',                  ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_thrown_poisonbottle']             = {['name'] = 'weapon_thrown_poisonbottle',             ['attachPoint'] = 6,  ['label'] = 'Poison Bottle',        ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_thrown_poisonbottle.png',             ['unique'] = false, ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    -- kit
    ['weapon_kit_metal_detector']              = {['name'] = 'weapon_kit_metal_detector',              ['attachPoint'] = 11, ['label'] = 'Metal Detector',       ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_kit_metal_detector.png',              ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_fishingrod']                      = {['name'] = 'weapon_fishingrod',                      ['attachPoint'] = 13, ['label'] = 'Fishingrod',           ['weight'] = 500,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_fishingrod.png',                      ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Fishingrod'},
    ['weapon_kit_binoculars']                  = {['name'] = 'weapon_kit_binoculars',                  ['attachPoint'] = 11, ['label'] = 'Binoculars',           ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_kit_binoculars.png',                  ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},
    ['weapon_kit_binoculars_improved']         = {['name'] = 'weapon_kit_binoculars_improved',         ['attachPoint'] = 11, ['label'] = 'Binoculars Improved',  ['weight'] = 100,  ['type'] = 'weapon', ['ammotype'] = nil,             ['image'] = 'weapon_kit_binoculars_improved.png',         ['unique'] = true,  ['useable'] = true, ['level'] = 0, ['description'] = 'Placeholder'},

    -- Bird Post
    ['birdpost'] = {['name'] = 'birdpost', ['label'] = 'Bird Post', ['weight'] = 5, ['type'] = 'item', ['image'] = 'birdpost.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Bird Post for sending letters'},

    -- Money Clip
    ['moneyclip'] = {['name'] = 'moneyclip', ['label'] = 'Money Clip', ['weight'] = 1, ['type'] = 'item', ['image'] = 'money_moneyclip.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Money Clip'},
}
